trigger:
- main

jobs:
- job: SetUpJava
  displayName: 'Set up Java 17'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
  - script: |
      java -version
    displayName: 'Verify Java Version'
  - script: |
      echo "Java setup complete"
    displayName: 'Confirmation Step'

- job: NodeSetup
  displayName: 'Node.js Setup'
  dependsOn: SetUpJava
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.15.1'
    displayName: 'Install Node.js'
  
  - script: |
      npm install
      npm run android
    displayName: 'npm install and build'