trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: /usr/lib/jvm/jdk-17

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y wget tar unzip
    wget https://download.java.net/java/GA/jdk17/35/GPL/openjdk-17_linux-x64_bin.tar.gz
    tar -xvf openjdk-17_linux-x64_bin.tar.gz
    sudo mv jdk-17 /usr/lib/jvm/
    sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17/bin/java 1
    sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-17/bin/javac 1
    sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java
    sudo update-alternatives --set javac /usr/lib/jvm/jdk-17/bin/javac
    echo "JAVA_HOME is set to $JAVA_HOME"
    echo "Checking Java installation"
    ls -l /usr/lib/jvm
    java -version
  displayName: 'Install and Verify Java 17'

- script: |
    wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
    export PATH=$PATH:$HOME/android-sdk/cmdline-tools/bin
    yes | sdkmanager --licenses
    sdkmanager "platform-tools" "platforms;android-30"
  displayName: 'Install Android SDK and Platform Tools'

- script: |
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
  displayName: 'Verify Java Installation'

- task: NodeTool@0
  inputs:
    versionSpec: '20.15.1'
  displayName: 'Install Node.js'
  env:
    JAVA_HOME: $(JAVA_HOME)

- script: |
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
    npm install
    npm run android || echo "npm run android failed"
  displayName: 'npm install and build'
  env:
    JAVA_HOME: $(JAVA_HOME)