trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: /usr/lib/jvm/jdk-17

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y wget tar unzip
    echo "Downloading Java..."
    wget -O openjdk-17.0.2_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz || { echo "Download failed"; exit 1; }
    echo "Extracting Java..."
    tar -xvf openjdk-17.0.2_linux-x64_bin.tar.gz || { echo "Extraction failed"; exit 1; }
    sudo mv jdk-17.0.2 /usr/lib/jvm/jdk-17
    sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17/bin/java 1
    sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-17/bin/javac 1
    sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java
    sudo update-alternatives --set javac /usr/lib/jvm/jdk-17/bin/javac
    echo "JAVA_HOME is set to $JAVA_HOME"
    ls -l /usr/lib/jvm
    java -version
    if [ ! -d "/usr/lib/jvm/jdk-17" ]; then
      echo "Directory /usr/lib/jvm/jdk-17 does not exist"
      exit 1
    fi
  displayName: 'Install and Verify Java 17'

- script: |
    wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    mkdir -p $HOME/android-sdk/cmdline-tools
    unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
    mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
    export ANDROID_SDK_ROOT=$HOME/android-sdk
    export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
    yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "platforms;android-31" "platforms;android-32" "platforms;android-33" "platforms;android-34"
  displayName: 'Install Android SDK and Platform Tools'

- task: NodeTool@0
  inputs:
    versionSpec: '20.15.1'
  displayName: 'Install Node.js'
  env:
    JAVA_HOME: $(JAVA_HOME)

- script: |
    export JAVA_HOME=/usr/lib/jvm/jdk-17
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
    npm install
    cd android
    ./gradlew assembleDebug
  displayName: 'npm install and build'
  env:
    JAVA_HOME: $(JAVA_HOME)